import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("auth/register", "routes/auth.register.tsx"),
  route("auth/login", "routes/auth.login.tsx"),
  route("auth/verify-email", "routes/auth.verify-email.tsx"),
  route("auth/2fa", "routes/auth.2fa.tsx"),
  route("auth/2fa/confirm", "routes/auth.2fa.confirm.tsx"),
  route("auth/logout", "routes/auth.logout.tsx"),
  route("api/auth/register", "routes/api.auth.register.ts"),
  route("api/auth/login", "routes/api.auth.login.ts"),
  route("api/2fa/setup/start", "routes/api.2fa.setup.start.ts"),
  route("api/2fa/setup/confirm", "routes/api.2fa.setup.confirm.ts"),
  route("api/2fa/verify", "routes/api.2fa.verify.ts"),
  route("api/2fa/confirm-action", "routes/api.2fa.confirm-action.ts"),
  route("api/2fa/disable", "routes/api.2fa.disable.ts"),
  route("api/2fa/backup-codes/regenerate", "routes/api.2fa.backup-codes.regenerate.ts"),
  route("api/security/preferences", "routes/api.security.preferences.ts"),
  route("api/preferences/theme", "routes/api.preferences.theme.ts"),
  route("api/notes", "routes/api.notes.ts"),
  route("api/notes/:noteId", "routes/api.notes.$noteId.ts"),
  route("api/notes/:noteId/critical", "routes/api.notes.$noteId.critical.ts"),
  route("api/vault", "routes/api.vault.ts"),
  route("app", "routes/app.tsx"),
  route("settings/security", "routes/settings.security.tsx"),
  route("settings/security/2fa/setup", "routes/settings.security.2fa.setup.tsx"),
  route("settings/security/2fa/backup-codes", "routes/settings.security.2fa.backup-codes.tsx"),
] satisfies RouteConfig;
