import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("auth/register", "routes/auth.register.tsx"),
  route("auth/login", "routes/auth.login.tsx"),
  route("auth/verify-email", "routes/auth.verify-email.tsx"),
  route("auth/2fa", "routes/auth.2fa.tsx"),
  route("auth/2fa/confirm", "routes/auth.2fa.confirm.tsx"),
  route("auth/logout", "routes/auth.logout.tsx"),
  route("api/auth/register", "routes/api.auth.register.ts"),
  route("api/auth/login", "routes/api.auth.login.ts"),
  route("api/2fa/setup/start", "routes/api.2fa.setup.start.ts"),
  route("api/2fa/setup/confirm", "routes/api.2fa.setup.confirm.ts"),
  route("api/2fa/verify", "routes/api.2fa.verify.ts"),
  route("api/2fa/confirm-action", "routes/api.2fa.confirm-action.ts"),
  route("api/2fa/disable", "routes/api.2fa.disable.ts"),
  route("api/2fa/backup-codes/regenerate", "routes/api.2fa.backup-codes.regenerate.ts"),
  route("api/security/preferences", "routes/api.security.preferences.ts"),
  route("api/preferences/theme", "routes/api.preferences.theme.ts"),
  route("api/preferences/background", "routes/api.preferences.background.ts"),
  route("api/unsplash/search", "routes/api.unsplash.search.ts"),
  route("api/unsplash/download", "routes/api.unsplash.download.ts"),
  route("api/favicon", "routes/api.favicon.ts"),
  route("api/notes", "routes/api.notes.ts"),
  route("api/notes/:noteId", "routes/api.notes.$noteId.ts"),
  route("api/notes/:noteId/critical", "routes/api.notes.$noteId.critical.ts"),
  route("api/notes/:noteId/folder", "routes/api.notes.$noteId.folder.ts"),
  route("api/vault", "routes/api.vault.ts"),
  route("api/vault-items", "routes/api.vault-items.ts"),
  route("api/vault-items/copy-authorize", "routes/api.vault-items.copy-authorize.ts"),
  route("api/vault-items/:itemId", "routes/api.vault-items.$itemId.ts"),
  route("api/vault-items/:itemId/folder", "routes/api.vault-items.$itemId.folder.ts"),
  route("api/vault-items/:itemId/favorite", "routes/api.vault-items.$itemId.favorite.ts"),
  route("api/vault-items/:itemId/pinned", "routes/api.vault-items.$itemId.pinned.ts"),
  route("api/vault-items/:itemId/archive", "routes/api.vault-items.$itemId.archive.ts"),
  route("api/vault-items/:itemId/recent-2fa", "routes/api.vault-items.$itemId.recent-2fa.ts"),
  route("api/vault-items/:itemId/tags", "routes/api.vault-items.$itemId.tags.ts"),
  route("api/vault-items/:itemId/item-notes", "routes/api.vault-items.$itemId.item-notes.ts"),
  route("api/vault-items/:itemId/events", "routes/api.vault-items.$itemId.events.ts"),
  route("api/folders", "routes/api.folders.ts"),
  route("api/folders/:folderId", "routes/api.folders.$folderId.ts"),
  route("api/folders/:folderId/move", "routes/api.folders.$folderId.move.ts"),
  route("api/workspace", "routes/api.workspace.ts"),
  route("app", "routes/app.tsx"),
  route("settings/security", "routes/settings.security.tsx"),
  route("settings/appearance", "routes/settings.appearance.tsx"),
  route("settings/security/2fa/setup", "routes/settings.security.2fa.setup.tsx"),
  route("settings/security/2fa/backup-codes", "routes/settings.security.2fa.backup-codes.tsx"),
] satisfies RouteConfig;
